-- 0001_initial.sql
-- Squashed initial schema for the unreleased MemoryCore migration set.
-- schema_migrations is managed by the Go migration runner.
-- memory_search_fts is created separately when EnableFTS=true.

-- Begin 0001_foundation.sql
-- 0001_memory_foundation.sql
-- EmoAgent MemoryGraph v2 authoritative SQLite foundation.
-- Apply with foreign keys enabled. IDs are ULID-compatible TEXT generated by application code.



CREATE TABLE IF NOT EXISTS personas (
    id                 TEXT PRIMARY KEY,
    display_name       TEXT NOT NULL,
    description        TEXT,
    status             TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'disabled', 'archived')),
    created_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
    id                 TEXT PRIMARY KEY,
    persona_id         TEXT NOT NULL,
    channel            TEXT NOT NULL DEFAULT 'webui'
        CHECK (channel IN ('webui', 'telegram', 'qq', 'cli', 'api', 'imported', 'other')),
    external_ref       TEXT,
    started_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at           TEXT,
    title              TEXT,
    summary            TEXT,
    visibility_status  TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'redacted', 'purged')),
    created_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TEXT,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    CHECK (ended_at IS NULL OR ended_at >= started_at)
);

CREATE TABLE IF NOT EXISTS episodes (
    id                 TEXT PRIMARY KEY,
    persona_id         TEXT NOT NULL,
    session_id         TEXT NOT NULL,
    role               TEXT NOT NULL
        CHECK (role IN ('user', 'assistant', 'system', 'tool_summary', 'work_report')),
    content            TEXT NOT NULL,
    content_hash       TEXT NOT NULL,
    occurred_at        TEXT NOT NULL,
    ingested_at        TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_type        TEXT NOT NULL
        CHECK (source_type IN ('chat', 'work_candidate', 'plugin', 'system', 'imported')),
    source_ref         TEXT,
    prev_episode_id    TEXT,
    next_episode_id    TEXT,
    visibility_status  TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'redacted', 'purged')),
    sensitivity_level  TEXT NOT NULL DEFAULT 'normal'
        CHECK (sensitivity_level IN ('normal', 'sensitive', 'highly_sensitive')),
    searchable         INTEGER NOT NULL DEFAULT 1
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (prev_episode_id) REFERENCES episodes(id) ON DELETE SET NULL,
    FOREIGN KEY (next_episode_id) REFERENCES episodes(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS episode_tombstones (
    episode_id                    TEXT PRIMARY KEY,
    persona_id                    TEXT NOT NULL,
    session_id                    TEXT,
    occurred_at                   TEXT,
    redacted_at                   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    redaction_level               TEXT NOT NULL
        CHECK (redaction_level IN ('source_redact', 'purge')),
    redaction_actor               TEXT NOT NULL
        CHECK (redaction_actor IN ('user', 'system', 'admin')),
    redaction_reason_code          TEXT NOT NULL
        CHECK (redaction_reason_code IN ('user_requested', 'retention_policy', 'safety', 'admin_policy')),
    source_type                   TEXT,
    source_ref_hash               TEXT,
    content_hash_before_redaction TEXT,
    audit_note                    TEXT,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS entities (
    id                 TEXT PRIMARY KEY,
    persona_id         TEXT NOT NULL,
    canonical_name     TEXT NOT NULL,
    entity_type        TEXT NOT NULL
        CHECK (entity_type IN ('user', 'agent', 'person', 'place', 'org', 'concept', 'object', 'event_topic')),
    description        TEXT,
    created_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TEXT,
    visibility_status  TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'forgotten', 'purged')),
    sensitivity_level  TEXT NOT NULL DEFAULT 'normal'
        CHECK (sensitivity_level IN ('normal', 'sensitive', 'highly_sensitive')),
    searchable         INTEGER NOT NULL DEFAULT 1
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS entity_aliases (
    id                 TEXT PRIMARY KEY,
    persona_id         TEXT NOT NULL,
    entity_id          TEXT NOT NULL,
    alias              TEXT NOT NULL,
    alias_type         TEXT NOT NULL DEFAULT 'surface'
        CHECK (alias_type IN ('surface', 'nickname', 'translation', 'abbreviation')),
    confidence         REAL NOT NULL DEFAULT 1.0
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    source_episode_id  TEXT,
    created_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE,
    FOREIGN KEY (source_episode_id) REFERENCES episodes(id) ON DELETE SET NULL,
    UNIQUE (persona_id, entity_id, alias, alias_type)
);

CREATE TABLE IF NOT EXISTS facts (
    id                         TEXT PRIMARY KEY,
    persona_id                 TEXT NOT NULL,
    subject_entity_id           TEXT,
    predicate                   TEXT NOT NULL,
    object_entity_id            TEXT,
    object_literal              TEXT,
    content_summary             TEXT NOT NULL,
    fact_type                   TEXT NOT NULL
        CHECK (fact_type IN (
            'core_identity',
            'significant_event',
            'stable_preference',
            'relational_state',
            'commitment',
            'transient_context',
            'task_relevant_context'
        )),
    valid_from                  TEXT,
    valid_to                    TEXT,
    ingested_at                 TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    extraction_confidence       TEXT NOT NULL
        CHECK (extraction_confidence IN ('explicit', 'inferred', 'ambiguous')),
    extraction_confidence_score REAL NOT NULL DEFAULT 0.5
        CHECK (extraction_confidence_score >= 0.0 AND extraction_confidence_score <= 1.0),
    extraction_reasoning        TEXT,
    importance                  REAL NOT NULL DEFAULT 0.5
        CHECK (importance >= 0.0 AND importance <= 1.0),
    valence                     REAL NOT NULL DEFAULT 0.0
        CHECK (valence >= -1.0 AND valence <= 1.0),
    arousal                     REAL NOT NULL DEFAULT 0.0
        CHECK (arousal >= 0.0 AND arousal <= 1.0),
    sensitivity_level           TEXT NOT NULL DEFAULT 'normal'
        CHECK (sensitivity_level IN ('normal', 'sensitive', 'highly_sensitive')),
    validity_status             TEXT NOT NULL DEFAULT 'valid'
        CHECK (validity_status IN ('valid', 'invalidated', 'uncertain')),
    visibility_status           TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'forgotten', 'purged')),
    lifecycle_status            TEXT NOT NULL DEFAULT 'active'
        CHECK (lifecycle_status IN ('active', 'dormant', 'consolidated', 'archived', 'deep_archived')),
    pinned                      INTEGER NOT NULL DEFAULT 0
        CHECK (pinned IN (0, 1)),
    pin_reason                  TEXT,
    pin_actor                   TEXT
        CHECK (pin_actor IS NULL OR pin_actor IN ('user', 'system', 'admin')),
    pinned_at                   TEXT,
    access_count                INTEGER NOT NULL DEFAULT 0
        CHECK (access_count >= 0),
    last_accessed_at            TEXT,
    reinforcement_count         INTEGER NOT NULL DEFAULT 0
        CHECK (reinforcement_count >= 0),
    congruent_access_count      INTEGER NOT NULL DEFAULT 0
        CHECK (congruent_access_count >= 0),
    searchable                  INTEGER NOT NULL DEFAULT 1
        CHECK (searchable IN (0, 1)),
    created_at                  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TEXT,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (subject_entity_id) REFERENCES entities(id) ON DELETE SET NULL,
    FOREIGN KEY (object_entity_id) REFERENCES entities(id) ON DELETE SET NULL,
    CHECK (
        object_entity_id IS NOT NULL
        OR object_literal IS NOT NULL
        OR visibility_status IN ('forgotten', 'purged')
    ),
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from),
    CHECK ((pinned = 0 AND pinned_at IS NULL) OR (pinned = 1))
);

CREATE TABLE IF NOT EXISTS narratives (
    id                    TEXT PRIMARY KEY,
    persona_id            TEXT NOT NULL,
    scope                 TEXT NOT NULL
        CHECK (scope IN ('day', 'week', 'month', 'topic', 'relationship_phase', 'project')),
    scope_ref             TEXT,
    summary               TEXT NOT NULL,
    emotional_tone        TEXT,
    valence_avg           REAL
        CHECK (valence_avg IS NULL OR (valence_avg >= -1.0 AND valence_avg <= 1.0)),
    arousal_avg           REAL
        CHECK (arousal_avg IS NULL OR (arousal_avg >= 0.0 AND arousal_avg <= 1.0)),
    importance            REAL NOT NULL DEFAULT 0.5
        CHECK (importance >= 0.0 AND importance <= 1.0),
    valid_from            TEXT,
    valid_to              TEXT,
    generated_at          TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    visibility_status     TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'forgotten', 'purged')),
    lifecycle_status      TEXT NOT NULL DEFAULT 'active'
        CHECK (lifecycle_status IN ('active', 'dormant', 'consolidated', 'archived', 'deep_archived')),
    sensitivity_level     TEXT NOT NULL DEFAULT 'normal'
        CHECK (sensitivity_level IN ('normal', 'sensitive', 'highly_sensitive')),
    searchable            INTEGER NOT NULL DEFAULT 1
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

CREATE TABLE IF NOT EXISTS insights (
    id                    TEXT PRIMARY KEY,
    persona_id            TEXT NOT NULL,
    insight_type          TEXT NOT NULL
        CHECK (insight_type IN ('pattern', 'trait', 'preference', 'boundary', 'coping_strategy', 'risk_signal')),
    content               TEXT NOT NULL,
    confidence            REAL NOT NULL DEFAULT 0.5
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    importance            REAL NOT NULL DEFAULT 0.5
        CHECK (importance >= 0.0 AND importance <= 1.0),
    valence               REAL NOT NULL DEFAULT 0.0
        CHECK (valence >= -1.0 AND valence <= 1.0),
    arousal               REAL NOT NULL DEFAULT 0.0
        CHECK (arousal >= 0.0 AND arousal <= 1.0),
    created_at            TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TEXT,
    visibility_status     TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'forgotten', 'purged')),
    lifecycle_status      TEXT NOT NULL DEFAULT 'active'
        CHECK (lifecycle_status IN ('active', 'dormant', 'consolidated', 'archived', 'deep_archived')),
    sensitivity_level     TEXT NOT NULL DEFAULT 'normal'
        CHECK (sensitivity_level IN ('normal', 'sensitive', 'highly_sensitive')),
    searchable            INTEGER NOT NULL DEFAULT 1
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sessions_persona_started
    ON sessions(persona_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_visibility
    ON sessions(persona_id, visibility_status, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_episodes_persona_session_time
    ON episodes(persona_id, session_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_episodes_persona_time
    ON episodes(persona_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_episodes_content_hash
    ON episodes(persona_id, content_hash);
CREATE INDEX IF NOT EXISTS idx_episodes_prev
    ON episodes(persona_id, prev_episode_id);
CREATE INDEX IF NOT EXISTS idx_episodes_next
    ON episodes(persona_id, next_episode_id);
CREATE INDEX IF NOT EXISTS idx_episodes_visible_searchable
    ON episodes(persona_id, occurred_at DESC)
    WHERE visibility_status = 'visible' AND searchable = 1;

CREATE INDEX IF NOT EXISTS idx_episode_tombstones_persona_time
    ON episode_tombstones(persona_id, redacted_at DESC);

CREATE INDEX IF NOT EXISTS idx_entities_persona_type_name
    ON entities(persona_id, entity_type, canonical_name);
CREATE INDEX IF NOT EXISTS idx_entities_persona_visible
    ON entities(persona_id, visibility_status, searchable);
CREATE INDEX IF NOT EXISTS idx_entity_aliases_persona_alias
    ON entity_aliases(persona_id, alias);
CREATE INDEX IF NOT EXISTS idx_entity_aliases_entity
    ON entity_aliases(entity_id);

CREATE INDEX IF NOT EXISTS idx_facts_subject_predicate
    ON facts(persona_id, subject_entity_id, predicate);
CREATE INDEX IF NOT EXISTS idx_facts_object_entity
    ON facts(persona_id, object_entity_id);
CREATE INDEX IF NOT EXISTS idx_facts_predicate
    ON facts(persona_id, predicate);
CREATE INDEX IF NOT EXISTS idx_facts_type_lifecycle
    ON facts(persona_id, fact_type, lifecycle_status);
CREATE INDEX IF NOT EXISTS idx_facts_validity_visibility
    ON facts(persona_id, validity_status, visibility_status, searchable);
CREATE INDEX IF NOT EXISTS idx_facts_pinned
    ON facts(persona_id, pinned, importance DESC, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_facts_ingested
    ON facts(persona_id, ingested_at DESC);
CREATE INDEX IF NOT EXISTS idx_facts_valid_time
    ON facts(persona_id, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS idx_facts_active_searchable
    ON facts(persona_id, importance DESC, ingested_at DESC)
    WHERE visibility_status = 'visible'
      AND searchable = 1
      AND lifecycle_status IN ('active', 'dormant', 'consolidated')
      AND validity_status IN ('valid', 'uncertain');

CREATE INDEX IF NOT EXISTS idx_narratives_scope
    ON narratives(persona_id, scope, scope_ref, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_narratives_searchable
    ON narratives(persona_id, importance DESC, generated_at DESC)
    WHERE visibility_status = 'visible' AND searchable = 1;

CREATE INDEX IF NOT EXISTS idx_insights_type
    ON insights(persona_id, insight_type, confidence DESC, importance DESC);
CREATE INDEX IF NOT EXISTS idx_insights_searchable
    ON insights(persona_id, importance DESC, created_at DESC)
    WHERE visibility_status = 'visible' AND searchable = 1;


-- Begin 0002_graph_policy_index.sql
-- 0002_memory_graph_policy_index.sql
-- Predicate schemas, graph links, entity co-occurrence, Trivium mirror mapping and async sync queue.


CREATE TABLE IF NOT EXISTS predicate_schemas (
    predicate             TEXT PRIMARY KEY,
    canonical_label       TEXT,
    default_fact_type     TEXT
        CHECK (default_fact_type IS NULL OR default_fact_type IN (
            'core_identity',
            'significant_event',
            'stable_preference',
            'relational_state',
            'commitment',
            'transient_context',
            'task_relevant_context'
        )),
    cardinality           TEXT NOT NULL
        CHECK (cardinality IN ('single', 'multi', 'temporal_multi')),
    conflict_policy       TEXT NOT NULL
        CHECK (conflict_policy IN ('supersede', 'coexist', 'merge', 'llm_check', 'expire_by_time')),
    temporal_behavior     TEXT NOT NULL
        CHECK (temporal_behavior IN ('state', 'event', 'preference', 'habit', 'commitment')),
    object_kind           TEXT NOT NULL
        CHECK (object_kind IN ('entity', 'literal', 'either')),
    default_tau_days      REAL
        CHECK (default_tau_days IS NULL OR default_tau_days > 0),
    default_importance    REAL NOT NULL DEFAULT 0.5
        CHECK (default_importance >= 0.0 AND default_importance <= 1.0),
    allow_inference       INTEGER NOT NULL DEFAULT 1
        CHECK (allow_inference IN (0, 1)),
    sensitive_by_default  INTEGER NOT NULL DEFAULT 0
        CHECK (sensitive_by_default IN (0, 1))
);

CREATE TABLE IF NOT EXISTS memory_links (
    id                 TEXT PRIMARY KEY,
    persona_id         TEXT NOT NULL,
    from_node_type     TEXT NOT NULL
        CHECK (from_node_type IN (
            'episode', 'entity', 'fact', 'narrative', 'insight', 'mood_state', 'affect_event',
            'agent_affect_profile', 'agent_affect_state', 'agent_appraisal', 'agent_affect_event',
            'agent_expression_decision', 'deletion_event'
        )),
    from_node_id       TEXT NOT NULL,
    link_type          TEXT NOT NULL
        CHECK (link_type IN (
            'EVIDENCED_BY', 'DERIVED_FROM', 'SUPERSEDES', 'CONTRADICTS',
            'CAUSED_BY', 'CONTRIBUTED_TO', 'TRIGGERED_BY', 'EXPLAINS',
            'ABOUT_ENTITY', 'CO_OCCURS_WITH', 'TEMPORAL_PREV', 'TEMPORAL_NEXT',
            'SUPPORTS', 'INHIBITS', 'REDACTED_BY'
        )),
    to_node_type       TEXT NOT NULL
        CHECK (to_node_type IN (
            'episode', 'entity', 'fact', 'narrative', 'insight', 'mood_state', 'affect_event',
            'agent_affect_profile', 'agent_affect_state', 'agent_appraisal', 'agent_affect_event',
            'agent_expression_decision', 'deletion_event'
        )),
    to_node_id         TEXT NOT NULL,
    direction          TEXT NOT NULL DEFAULT 'forward'
        CHECK (direction IN ('forward', 'backward', 'bidirectional')),
    confidence         REAL NOT NULL DEFAULT 1.0
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    weight             REAL NOT NULL DEFAULT 1.0
        CHECK (weight >= -1.0 AND weight <= 1.0),
    reasoning          TEXT,
    valid_from         TEXT,
    valid_to           TEXT,
    created_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         TEXT NOT NULL DEFAULT 'system'
        CHECK (created_by IN ('system', 'llm', 'user', 'consolidation')),
    visibility_status  TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'forgotten', 'purged')),
    searchable         INTEGER NOT NULL DEFAULT 1
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    UNIQUE (persona_id, from_node_type, from_node_id, link_type, to_node_type, to_node_id),
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

CREATE TABLE IF NOT EXISTS entity_cooccurrences (
    id               TEXT PRIMARY KEY,
    persona_id       TEXT NOT NULL,
    entity_a_id      TEXT NOT NULL,
    entity_b_id      TEXT NOT NULL,
    co_count         INTEGER NOT NULL DEFAULT 1
        CHECK (co_count >= 1),
    last_seen_at     TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    context_scope    TEXT NOT NULL DEFAULT 'session'
        CHECK (context_scope IN ('message_window', 'session', 'week', 'topic')),
    confidence       REAL NOT NULL DEFAULT 0.5
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (entity_a_id) REFERENCES entities(id) ON DELETE CASCADE,
    FOREIGN KEY (entity_b_id) REFERENCES entities(id) ON DELETE CASCADE,
    UNIQUE (persona_id, entity_a_id, entity_b_id, context_scope),
    CHECK (entity_a_id <> entity_b_id)
);

CREATE TABLE IF NOT EXISTS memory_index_map (
    id                TEXT PRIMARY KEY,
    persona_id        TEXT NOT NULL,
    node_type         TEXT NOT NULL
        CHECK (node_type IN (
            'episode', 'entity', 'fact', 'narrative', 'insight', 'mood_state', 'affect_event',
            'agent_affect_profile', 'agent_affect_state', 'agent_appraisal', 'agent_affect_event',
            'agent_expression_decision', 'deletion_event'
        )),
    node_id           TEXT NOT NULL,
    trivium_node_id   INTEGER NOT NULL,
    index_status      TEXT NOT NULL
        CHECK (index_status IN ('pending', 'indexed', 'stale', 'deleted', 'failed', 'stale_delete_failed')),
    indexed_at        TEXT,
    updated_at        TEXT,
    error_message     TEXT,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    UNIQUE (persona_id, node_type, node_id),
    UNIQUE (persona_id, trivium_node_id)
);

CREATE TABLE IF NOT EXISTS index_sync_queue (
    id             TEXT PRIMARY KEY,
    persona_id     TEXT NOT NULL,
    node_type      TEXT NOT NULL
        CHECK (node_type IN (
            'episode', 'entity', 'fact', 'narrative', 'insight', 'mood_state', 'affect_event',
            'agent_affect_profile', 'agent_affect_state', 'agent_appraisal', 'agent_affect_event',
            'agent_expression_decision', 'deletion_event', 'memory_link', 'persona'
        )),
    node_id        TEXT NOT NULL,
    operation      TEXT NOT NULL
        CHECK (operation IN ('upsert_node', 'delete_node', 'upsert_edge', 'delete_edge', 'rebuild_persona')),
    priority       INTEGER NOT NULL DEFAULT 5
        CHECK (priority >= 0 AND priority <= 10),
    payload_json   TEXT,
    status         TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing', 'done', 'failed')),
    attempts       INTEGER NOT NULL DEFAULT 0
        CHECK (attempts >= 0),
    created_at     TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TEXT,
    error_message  TEXT,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_predicate_schemas_type
    ON predicate_schemas(default_fact_type, cardinality, conflict_policy);

CREATE INDEX IF NOT EXISTS idx_memory_links_from
    ON memory_links(persona_id, from_node_type, from_node_id);
CREATE INDEX IF NOT EXISTS idx_memory_links_to
    ON memory_links(persona_id, to_node_type, to_node_id);
CREATE INDEX IF NOT EXISTS idx_memory_links_type
    ON memory_links(persona_id, link_type);
CREATE INDEX IF NOT EXISTS idx_memory_links_from_type
    ON memory_links(persona_id, from_node_type, from_node_id, link_type);
CREATE INDEX IF NOT EXISTS idx_memory_links_to_type
    ON memory_links(persona_id, to_node_type, to_node_id, link_type);
CREATE INDEX IF NOT EXISTS idx_memory_links_visible_searchable
    ON memory_links(persona_id, link_type, weight DESC)
    WHERE visibility_status = 'visible' AND searchable = 1;

CREATE INDEX IF NOT EXISTS idx_entity_cooccurrences_a
    ON entity_cooccurrences(persona_id, entity_a_id, context_scope, co_count DESC);
CREATE INDEX IF NOT EXISTS idx_entity_cooccurrences_b
    ON entity_cooccurrences(persona_id, entity_b_id, context_scope, co_count DESC);
CREATE INDEX IF NOT EXISTS idx_entity_cooccurrences_last_seen
    ON entity_cooccurrences(persona_id, last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_memory_index_map_node
    ON memory_index_map(persona_id, node_type, node_id);
CREATE INDEX IF NOT EXISTS idx_memory_index_map_trivium
    ON memory_index_map(persona_id, trivium_node_id);
CREATE INDEX IF NOT EXISTS idx_memory_index_map_status
    ON memory_index_map(persona_id, index_status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_index_sync_queue_pending
    ON index_sync_queue(status, priority ASC, created_at ASC)
    WHERE status IN ('pending', 'failed');
CREATE INDEX IF NOT EXISTS idx_index_sync_queue_persona_node
    ON index_sync_queue(persona_id, node_type, node_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_index_sync_queue_operation
    ON index_sync_queue(persona_id, operation, status, priority ASC);

INSERT OR IGNORE INTO predicate_schemas (
    predicate, canonical_label, default_fact_type, cardinality, conflict_policy,
    temporal_behavior, object_kind, default_tau_days, default_importance,
    allow_inference, sensitive_by_default
) VALUES
    ('lives_in', '居住地', 'core_identity', 'single', 'supersede', 'state', 'entity', 3650, 0.80, 1, 0),
    ('works_at', '工作单位', 'core_identity', 'single', 'supersede', 'state', 'entity', 1825, 0.75, 1, 0),
    ('prefers_name', '偏好称呼', 'core_identity', 'single', 'supersede', 'preference', 'literal', 3650, 0.85, 1, 0),
    ('likes', '喜欢', 'stable_preference', 'multi', 'coexist', 'preference', 'either', 365, 0.55, 1, 0),
    ('dislikes', '不喜欢', 'stable_preference', 'multi', 'coexist', 'preference', 'either', 365, 0.60, 1, 0),
    ('has_pet', '宠物', 'core_identity', 'multi', 'coexist', 'state', 'entity', 1825, 0.65, 1, 0),
    ('is_busy_with', '近期忙于', 'transient_context', 'temporal_multi', 'expire_by_time', 'state', 'either', 21, 0.50, 1, 0),
    ('feels_about_agent', '对 Agent 的感受', 'relational_state', 'single', 'llm_check', 'preference', 'literal', 180, 0.65, 1, 0),
    ('promised_to', '承诺/约定', 'commitment', 'temporal_multi', 'expire_by_time', 'commitment', 'literal', 30, 0.70, 1, 0),
    ('is_considering', '正在考虑', 'significant_event', 'temporal_multi', 'expire_by_time', 'event', 'either', 90, 0.65, 1, 0),
    ('has_boundary', '边界/禁忌', 'relational_state', 'multi', 'merge', 'preference', 'literal', 365, 0.80, 1, 1),
    ('prefers_communication_style', '沟通风格偏好', 'stable_preference', 'multi', 'merge', 'preference', 'literal', 365, 0.65, 1, 0),
    ('uses_coping_strategy', '应对方式', 'stable_preference', 'multi', 'coexist', 'habit', 'literal', 365, 0.65, 1, 0);


-- Begin 0003_affect_audit.sql
-- 0003_memory_affect_audit.sql
-- User/relationship mood, Agent Affect placeholders, deletion audit and access/fatigue events.


CREATE TABLE IF NOT EXISTS mood_states (
    id             TEXT PRIMARY KEY,
    persona_id     TEXT NOT NULL,
    scope          TEXT NOT NULL DEFAULT 'user'
        CHECK (scope IN ('user', 'relationship', 'conversation')),
    valence        REAL NOT NULL
        CHECK (valence >= -1.0 AND valence <= 1.0),
    arousal        REAL NOT NULL
        CHECK (arousal >= 0.0 AND arousal <= 1.0),
    confidence     REAL NOT NULL DEFAULT 0.5
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    label          TEXT,
    updated_at     TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS affect_events (
    id                 TEXT PRIMARY KEY,
    persona_id         TEXT NOT NULL,
    scope              TEXT NOT NULL DEFAULT 'user'
        CHECK (scope IN ('user', 'relationship', 'conversation')),
    trigger_type       TEXT NOT NULL
        CHECK (trigger_type IN ('user_message', 'memory_recall', 'idle_check', 'plugin', 'work_report', 'system_event')),
    trigger_ref        TEXT,
    mood_before_v      REAL CHECK (mood_before_v IS NULL OR (mood_before_v >= -1.0 AND mood_before_v <= 1.0)),
    mood_before_a      REAL CHECK (mood_before_a IS NULL OR (mood_before_a >= 0.0 AND mood_before_a <= 1.0)),
    mood_after_v       REAL CHECK (mood_after_v IS NULL OR (mood_after_v >= -1.0 AND mood_after_v <= 1.0)),
    mood_after_a       REAL CHECK (mood_after_a IS NULL OR (mood_after_a >= 0.0 AND mood_after_a <= 1.0)),
    delta_v            REAL CHECK (delta_v IS NULL OR (delta_v >= -2.0 AND delta_v <= 2.0)),
    delta_a            REAL CHECK (delta_a IS NULL OR (delta_a >= -1.0 AND delta_a <= 1.0)),
    emotion_label      TEXT,
    significance       REAL NOT NULL DEFAULT 0.5
        CHECK (significance >= 0.0 AND significance <= 1.0),
    reasoning          TEXT,
    created_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    visibility_status  TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'forgotten', 'purged')),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS agent_affect_profiles (
    id                         TEXT PRIMARY KEY,
    persona_id                 TEXT NOT NULL,
    profile_name               TEXT NOT NULL DEFAULT 'default',
    baseline_valence           REAL NOT NULL DEFAULT 0.0
        CHECK (baseline_valence >= -1.0 AND baseline_valence <= 1.0),
    baseline_arousal           REAL NOT NULL DEFAULT 0.2
        CHECK (baseline_arousal >= 0.0 AND baseline_arousal <= 1.0),
    baseline_dominance         REAL NOT NULL DEFAULT 0.0
        CHECK (baseline_dominance >= -1.0 AND baseline_dominance <= 1.0),
    baseline_warmth            REAL NOT NULL DEFAULT 0.6
        CHECK (baseline_warmth >= 0.0 AND baseline_warmth <= 1.0),
    baseline_concern           REAL NOT NULL DEFAULT 0.3
        CHECK (baseline_concern >= 0.0 AND baseline_concern <= 1.0),
    baseline_playfulness       REAL NOT NULL DEFAULT 0.2
        CHECK (baseline_playfulness >= 0.0 AND baseline_playfulness <= 1.0),
    baseline_curiosity         REAL NOT NULL DEFAULT 0.3
        CHECK (baseline_curiosity >= 0.0 AND baseline_curiosity <= 1.0),
    inertia                    REAL NOT NULL DEFAULT 0.7
        CHECK (inertia >= 0.0 AND inertia <= 1.0),
    decay_half_life_seconds    INTEGER NOT NULL DEFAULT 1800
        CHECK (decay_half_life_seconds > 0),
    affect_policy_version      TEXT NOT NULL DEFAULT 'agent_affect_v0',
    expression_policy_version  TEXT NOT NULL DEFAULT 'expression_policy_v0',
    config_json                TEXT,
    visibility_status          TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'purged')),
    searchable                 INTEGER NOT NULL DEFAULT 0
        CHECK (searchable IN (0, 1)),
    created_at                 TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TEXT,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    UNIQUE (persona_id, profile_name)
);

CREATE TABLE IF NOT EXISTS agent_affect_states (
    id                         TEXT PRIMARY KEY,
    persona_id                 TEXT NOT NULL,
    session_id                 TEXT,
    profile_id                 TEXT,
    valence                    REAL NOT NULL DEFAULT 0.0
        CHECK (valence >= -1.0 AND valence <= 1.0),
    arousal                    REAL NOT NULL DEFAULT 0.2
        CHECK (arousal >= 0.0 AND arousal <= 1.0),
    dominance                  REAL NOT NULL DEFAULT 0.0
        CHECK (dominance >= -1.0 AND dominance <= 1.0),
    warmth                     REAL NOT NULL DEFAULT 0.0
        CHECK (warmth >= 0.0 AND warmth <= 1.0),
    concern                    REAL NOT NULL DEFAULT 0.0
        CHECK (concern >= 0.0 AND concern <= 1.0),
    curiosity                  REAL NOT NULL DEFAULT 0.0
        CHECK (curiosity >= 0.0 AND curiosity <= 1.0),
    playfulness                REAL NOT NULL DEFAULT 0.0
        CHECK (playfulness >= 0.0 AND playfulness <= 1.0),
    frustration                REAL NOT NULL DEFAULT 0.0
        CHECK (frustration >= 0.0 AND frustration <= 1.0),
    attachment                 REAL NOT NULL DEFAULT 0.0
        CHECK (attachment >= 0.0 AND attachment <= 1.0),
    uncertainty                REAL NOT NULL DEFAULT 0.0
        CHECK (uncertainty >= 0.0 AND uncertainty <= 1.0),
    label                      TEXT,
    confidence                 REAL NOT NULL DEFAULT 0.5
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    state_vector_json          TEXT,
    affect_policy_version      TEXT NOT NULL DEFAULT 'agent_affect_v0',
    expression_policy_version  TEXT NOT NULL DEFAULT 'expression_policy_v0',
    updated_at                 TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at                 TEXT,
    visibility_status          TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'purged')),
    searchable                 INTEGER NOT NULL DEFAULT 0
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL,
    FOREIGN KEY (profile_id) REFERENCES agent_affect_profiles(id) ON DELETE SET NULL,
    CHECK (expires_at IS NULL OR expires_at >= updated_at)
);

CREATE TABLE IF NOT EXISTS agent_appraisals (
    id                         TEXT PRIMARY KEY,
    persona_id                 TEXT NOT NULL,
    session_id                 TEXT,
    trigger_type               TEXT NOT NULL
        CHECK (trigger_type IN (
            'user_message', 'memory_recall', 'relationship_event', 'safety_boundary',
            'self_reflection', 'work_report_summary', 'system_event'
        )),
    trigger_ref_type           TEXT,
    trigger_ref_id             TEXT,
    trigger_ref_hash           TEXT,
    target_node_type           TEXT,
    target_node_id             TEXT,
    appraisal_model            TEXT NOT NULL DEFAULT 'placeholder',
    appraisal_policy_version   TEXT NOT NULL DEFAULT 'agent_appraisal_v0',
    novelty                    REAL CHECK (novelty IS NULL OR (novelty >= 0.0 AND novelty <= 1.0)),
    goal_relevance             REAL CHECK (goal_relevance IS NULL OR (goal_relevance >= 0.0 AND goal_relevance <= 1.0)),
    relationship_impact        REAL CHECK (relationship_impact IS NULL OR (relationship_impact >= -1.0 AND relationship_impact <= 1.0)),
    boundary_violation         REAL CHECK (boundary_violation IS NULL OR (boundary_violation >= 0.0 AND boundary_violation <= 1.0)),
    controllability            REAL CHECK (controllability IS NULL OR (controllability >= 0.0 AND controllability <= 1.0)),
    uncertainty                REAL CHECK (uncertainty IS NULL OR (uncertainty >= 0.0 AND uncertainty <= 1.0)),
    expected_user_need         TEXT,
    safety_risk                REAL CHECK (safety_risk IS NULL OR (safety_risk >= 0.0 AND safety_risk <= 1.0)),
    appraisal_json             TEXT,
    confidence                 REAL NOT NULL DEFAULT 0.5
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    created_at                 TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    visibility_status          TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'purged')),
    searchable                 INTEGER NOT NULL DEFAULT 0
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS agent_affect_events (
    id                         TEXT PRIMARY KEY,
    persona_id                 TEXT NOT NULL,
    session_id                 TEXT,
    trigger_type               TEXT NOT NULL,
    trigger_ref_type           TEXT,
    trigger_ref_id             TEXT,
    trigger_ref_hash           TEXT,
    appraisal_id               TEXT,
    before_state_id            TEXT,
    after_state_id             TEXT,
    delta_json                 TEXT,
    label                      TEXT,
    significance               REAL NOT NULL DEFAULT 0.5
        CHECK (significance >= 0.0 AND significance <= 1.0),
    reason_summary             TEXT,
    created_at                 TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    visibility_status          TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'purged')),
    searchable                 INTEGER NOT NULL DEFAULT 0
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL,
    FOREIGN KEY (appraisal_id) REFERENCES agent_appraisals(id) ON DELETE SET NULL,
    FOREIGN KEY (before_state_id) REFERENCES agent_affect_states(id) ON DELETE SET NULL,
    FOREIGN KEY (after_state_id) REFERENCES agent_affect_states(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS agent_expression_decisions (
    id                         TEXT PRIMARY KEY,
    persona_id                 TEXT NOT NULL,
    session_id                 TEXT,
    message_id                 TEXT,
    agent_affect_state_id       TEXT,
    user_mood_state_id          TEXT,
    relationship_mood_state_id  TEXT,
    expression_policy_version   TEXT NOT NULL DEFAULT 'expression_policy_v0',
    guidance_json               TEXT NOT NULL,
    safety_overrides_json       TEXT,
    created_at                  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    visibility_status           TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'purged')),
    searchable                  INTEGER NOT NULL DEFAULT 0
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL,
    FOREIGN KEY (agent_affect_state_id) REFERENCES agent_affect_states(id) ON DELETE SET NULL,
    FOREIGN KEY (user_mood_state_id) REFERENCES mood_states(id) ON DELETE SET NULL,
    FOREIGN KEY (relationship_mood_state_id) REFERENCES mood_states(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS deletion_events (
    id                         TEXT PRIMARY KEY,
    persona_id                 TEXT NOT NULL,
    session_id                 TEXT,
    request_episode_id          TEXT,
    deletion_level             TEXT NOT NULL
        CHECK (deletion_level IN ('soft_forget', 'hard_forget', 'source_redact', 'purge')),
    target_node_type            TEXT,
    target_node_id              TEXT,
    actor                       TEXT NOT NULL
        CHECK (actor IN ('user', 'system', 'admin')),
    reason_code                 TEXT NOT NULL
        CHECK (reason_code IN ('user_requested', 'retention_policy', 'safety', 'admin_policy')),
    scope_json                  TEXT,
    cascade_summary_json        TEXT,
    status                      TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    created_at                  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at                TEXT,
    audit_note                  TEXT,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL,
    FOREIGN KEY (request_episode_id) REFERENCES episodes(id) ON DELETE SET NULL,
    CHECK (completed_at IS NULL OR completed_at >= created_at)
);

CREATE TABLE IF NOT EXISTS memory_access_events (
    id                         TEXT PRIMARY KEY,
    persona_id                 TEXT NOT NULL,
    session_id                 TEXT,
    message_id                 TEXT,
    node_type                  TEXT NOT NULL
        CHECK (node_type IN ('episode', 'entity', 'fact', 'narrative', 'insight', 'mood_state', 'affect_event')),
    node_id                    TEXT NOT NULL,
    access_type                TEXT NOT NULL DEFAULT 'retrieved'
        CHECK (access_type IN ('retrieved', 'prompt_injected', 'reinforced', 'suppressed', 'filtered')),
    retrieval_score            REAL,
    rank_position              INTEGER,
    score_breakdown_json       TEXT,
    activation_path_json       TEXT,
    context_block_type         TEXT,
    user_mood_label            TEXT,
    relationship_affect_label  TEXT,
    agent_affect_state_id       TEXT,
    created_at                 TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL,
    FOREIGN KEY (agent_affect_state_id) REFERENCES agent_affect_states(id) ON DELETE SET NULL,
    CHECK (rank_position IS NULL OR rank_position >= 0)
);

CREATE INDEX IF NOT EXISTS idx_mood_states_current
    ON mood_states(persona_id, scope, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_affect_events_time
    ON affect_events(persona_id, scope, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_affect_events_trigger
    ON affect_events(persona_id, trigger_type, trigger_ref);

CREATE INDEX IF NOT EXISTS idx_agent_affect_profiles_persona
    ON agent_affect_profiles(persona_id, profile_name);
CREATE INDEX IF NOT EXISTS idx_agent_affect_states_current
    ON agent_affect_states(persona_id, session_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_affect_states_profile
    ON agent_affect_states(persona_id, profile_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_appraisals_trigger
    ON agent_appraisals(persona_id, trigger_type, trigger_ref_type, trigger_ref_id);
CREATE INDEX IF NOT EXISTS idx_agent_appraisals_target
    ON agent_appraisals(persona_id, target_node_type, target_node_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_affect_events_time
    ON agent_affect_events(persona_id, session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_affect_events_appraisal
    ON agent_affect_events(persona_id, appraisal_id);
CREATE INDEX IF NOT EXISTS idx_agent_expression_decisions_message
    ON agent_expression_decisions(persona_id, session_id, message_id);

CREATE INDEX IF NOT EXISTS idx_deletion_events_persona_time
    ON deletion_events(persona_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_deletion_events_target
    ON deletion_events(persona_id, target_node_type, target_node_id);
CREATE INDEX IF NOT EXISTS idx_deletion_events_status
    ON deletion_events(persona_id, status, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_memory_access_events_node
    ON memory_access_events(persona_id, node_type, node_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_access_events_session
    ON memory_access_events(persona_id, session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_access_events_type
    ON memory_access_events(persona_id, access_type, created_at DESC);


-- Begin 0004_search_fallback_optional.sql
-- 0004_memory_search_fallback_optional.sql
-- Optional SQLite fallback search layer. Use this when TriviumDB/Python Sidecar is unavailable.
-- Requires SQLite FTS5 for memory_search_fts. If FTS5 is not available, keep only memory_search_documents.


CREATE TABLE IF NOT EXISTS memory_search_documents (
    id                 TEXT PRIMARY KEY,
    persona_id         TEXT NOT NULL,
    node_type          TEXT NOT NULL
        CHECK (node_type IN ('episode', 'entity', 'fact', 'narrative', 'insight')),
    node_id            TEXT NOT NULL,
    search_text        TEXT NOT NULL,
    search_tier        TEXT NOT NULL DEFAULT 'hot'
        CHECK (search_tier IN ('hot', 'warm', 'cold', 'deep_cold')),
    visibility_status  TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'forgotten', 'purged')),
    sensitivity_level  TEXT NOT NULL DEFAULT 'normal'
        CHECK (sensitivity_level IN ('normal', 'sensitive', 'highly_sensitive')),
    lifecycle_status   TEXT NOT NULL DEFAULT 'active'
        CHECK (lifecycle_status IN ('active', 'dormant', 'consolidated', 'archived', 'deep_archived')),
    searchable         INTEGER NOT NULL DEFAULT 1
        CHECK (searchable IN (0, 1)),
    updated_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    UNIQUE (persona_id, node_type, node_id)
);

CREATE INDEX IF NOT EXISTS idx_memory_search_documents_node
    ON memory_search_documents(persona_id, node_type, node_id);
CREATE INDEX IF NOT EXISTS idx_memory_search_documents_visible
    ON memory_search_documents(persona_id, search_tier, updated_at DESC)
    WHERE visibility_status = 'visible' AND searchable = 1;



-- Begin 0005_extraction_runtime.sql
-- 0005_extraction_runtime.sql
-- Phase 2C sanitized extraction run audit and idempotency metadata.

CREATE TABLE IF NOT EXISTS extraction_runs (
    id                         TEXT PRIMARY KEY,
    request_id                 TEXT NOT NULL,
    persona_id                 TEXT NOT NULL,
    session_id                 TEXT,
    trigger                    TEXT NOT NULL,
    mode                       TEXT NOT NULL
        CHECK (mode IN ('validate', 'dry-run', 'apply')),
    status                     TEXT NOT NULL
        CHECK (status IN (
            'skipped', 'validated', 'dry_run', 'applied',
            'nothing_applied', 'blocked', 'failed', 'partially_failed'
        )),
    fingerprint                TEXT NOT NULL,
    provider_id                TEXT NOT NULL DEFAULT '',
    provider_kind              TEXT NOT NULL DEFAULT '',
    model                      TEXT,
    prompt_version             TEXT NOT NULL DEFAULT '',
    prefilter_prompt_version   TEXT NOT NULL DEFAULT '',
    repair_prompt_version      TEXT NOT NULL DEFAULT '',
    original_episode_count     INTEGER NOT NULL DEFAULT 0,
    kept_episode_count         INTEGER NOT NULL DEFAULT 0,
    skipped_episode_count      INTEGER NOT NULL DEFAULT 0,
    accepted_count             INTEGER NOT NULL DEFAULT 0,
    review_count               INTEGER NOT NULL DEFAULT 0,
    rejected_count             INTEGER NOT NULL DEFAULT 0,
    routed_count               INTEGER NOT NULL DEFAULT 0,
    not_applied_count          INTEGER NOT NULL DEFAULT 0,
    applied_count              INTEGER NOT NULL DEFAULT 0,
    failure_count              INTEGER NOT NULL DEFAULT 0,
    prompt_hash                TEXT,
    response_hash              TEXT,
    repaired_response_hash     TEXT,
    prefilter_hash             TEXT,
    usage_prompt_tokens        INTEGER NOT NULL DEFAULT 0,
    usage_completion_tokens    INTEGER NOT NULL DEFAULT 0,
    usage_total_tokens         INTEGER NOT NULL DEFAULT 0,
    latency_ms                 INTEGER NOT NULL DEFAULT 0,
    duration_ms                INTEGER NOT NULL DEFAULT 0,
    sanitized_error_code       TEXT,
    sanitized_error_message    TEXT,
    created_at                 TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_extraction_runs_fingerprint_mode_status
    ON extraction_runs(fingerprint, mode, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_extraction_runs_persona_status
    ON extraction_runs(persona_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_extraction_runs_session
    ON extraction_runs(persona_id, session_id, trigger, created_at DESC);


-- Begin 0006_mirror_persona_state.sql
-- 0006_mirror_persona_state.sql
-- Persona-level mirror readiness gate for rebuild and retrieval fallback.

CREATE TABLE IF NOT EXISTS mirror_persona_state (
    persona_id   TEXT PRIMARY KEY,
    state        TEXT NOT NULL DEFAULT 'ready'
        CHECK (state IN ('ready', 'rebuilding', 'degraded')),
    reason       TEXT,
    updated_at   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mirror_persona_state_state
    ON mirror_persona_state(state, updated_at DESC);


-- Begin 0007_batch_prefetch_indexes.sql
CREATE INDEX IF NOT EXISTS idx_memory_access_events_session_node_access
    ON memory_access_events(session_id, node_type, node_id, access_type);


-- Begin 0008_consolidation_apply_fingerprints.sql
CREATE TABLE IF NOT EXISTS consolidation_apply_fingerprints (
    persona_id   TEXT NOT NULL,
    fingerprint  TEXT NOT NULL,
    fact_id      TEXT,
    candidate_id TEXT,
    request_id   TEXT,
    session_id   TEXT,
    action       TEXT NOT NULL,
    created_at   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (persona_id, fingerprint),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_consolidation_apply_fingerprints_fact
    ON consolidation_apply_fingerprints(persona_id, fact_id);

CREATE INDEX IF NOT EXISTS idx_consolidation_apply_fingerprints_session
    ON consolidation_apply_fingerprints(persona_id, session_id, created_at);


-- Begin 0009_consolidation_session_fact_writes.sql
CREATE TABLE IF NOT EXISTS consolidation_session_fact_writes (
    persona_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    fact_id    TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (persona_id, session_id, fact_id),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_consolidation_session_fact_writes_fact
    ON consolidation_session_fact_writes(persona_id, fact_id);


-- Begin 0010_natural_memory_dynamics.sql
CREATE TABLE IF NOT EXISTS memory_natural_states (
    persona_id                  TEXT NOT NULL,
    node_type                   TEXT NOT NULL
        CHECK (node_type IN ('fact', 'narrative', 'insight')),
    node_id                     TEXT NOT NULL,
    algorithm_version           TEXT NOT NULL DEFAULT 'natural_power_sleep_v1',
    natural_strength            REAL NOT NULL DEFAULT 1.0
        CHECK (natural_strength >= 0.0 AND natural_strength <= 1.5),
    retrievability              REAL NOT NULL DEFAULT 1.0
        CHECK (retrievability >= 0.0 AND retrievability <= 1.5),
    stability_days              REAL NOT NULL DEFAULT 1.0
        CHECK (stability_days >= 0.0),
    decay_exponent              REAL NOT NULL DEFAULT 0.6
        CHECK (decay_exponent >= 0.0),
    natural_state               TEXT NOT NULL DEFAULT 'salient'
        CHECK (natural_state IN ('salient', 'available', 'latent', 'faded', 'sleep_consolidated')),
    last_simulated_at           TEXT,
    last_reactivated_at         TEXT,
    last_strengthened_at        TEXT,
    first_sleep_consolidated    INTEGER NOT NULL DEFAULT 0
        CHECK (first_sleep_consolidated IN (0, 1)),
    reactivation_count          INTEGER NOT NULL DEFAULT 0
        CHECK (reactivation_count >= 0),
    protected_reason            TEXT,
    emotion_salience_hint       REAL NOT NULL DEFAULT 0.0
        CHECK (emotion_salience_hint >= 0.0 AND emotion_salience_hint <= 1.0),
    emotion_persistence_hint    REAL NOT NULL DEFAULT 0.0
        CHECK (emotion_persistence_hint >= 0.0 AND emotion_persistence_hint <= 1.0),
    score_breakdown_json        TEXT,
    updated_at                  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (persona_id, node_type, node_id)
);

CREATE TABLE IF NOT EXISTS memory_natural_events (
    id                          TEXT PRIMARY KEY,
    run_id                      TEXT,
    persona_id                  TEXT NOT NULL,
    node_type                   TEXT NOT NULL,
    node_id                     TEXT NOT NULL,
    event_type                  TEXT NOT NULL
        CHECK (event_type IN (
            'scored',
            'protected',
            'decayed',
            'reactivated',
            'first_sleep_consolidated',
            'natural_state_changed',
            'search_tier_updated',
            'compression_candidate_emitted',
            'storage_rewarm_candidate',
            'skipped'
        )),
    from_natural_state          TEXT,
    to_natural_state            TEXT,
    from_search_tier            TEXT,
    to_search_tier              TEXT,
    natural_strength            REAL,
    retrievability              REAL,
    stability_days              REAL,
    decay_exponent              REAL,
    reactivation_score          REAL,
    reason_codes_json           TEXT,
    safe_reason_summary         TEXT,
    created_at                  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS memory_natural_runs (
    id                          TEXT PRIMARY KEY,
    persona_id                  TEXT NOT NULL,
    run_kind                    TEXT NOT NULL
        CHECK (run_kind IN ('sleep_cycle', 'manual', 'api', 'test')),
    algorithm_version           TEXT NOT NULL DEFAULT 'natural_power_sleep_v1',
    local_date                  TEXT,
    local_time                  TEXT,
    timezone                    TEXT,
    dry_run                     INTEGER NOT NULL DEFAULT 0
        CHECK (dry_run IN (0, 1)),
    force                       INTEGER NOT NULL DEFAULT 0
        CHECK (force IN (0, 1)),
    mark_sleep_cycle            INTEGER NOT NULL DEFAULT 0
        CHECK (mark_sleep_cycle IN (0, 1)),
    started_at                  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at                TEXT,
    status                      TEXT NOT NULL
        CHECK (status IN ('running', 'completed', 'failed', 'skipped')),
    evaluated_nodes             INTEGER NOT NULL DEFAULT 0,
    scored_nodes                INTEGER NOT NULL DEFAULT 0,
    protected_nodes             INTEGER NOT NULL DEFAULT 0,
    decayed_nodes               INTEGER NOT NULL DEFAULT 0,
    reactivated_nodes           INTEGER NOT NULL DEFAULT 0,
    first_sleep_consolidated_nodes INTEGER NOT NULL DEFAULT 0,
    search_tier_updates         INTEGER NOT NULL DEFAULT 0,
    search_documents_created    INTEGER NOT NULL DEFAULT 0,
    mirror_updates_enqueued     INTEGER NOT NULL DEFAULT 0,
    compression_candidates      INTEGER NOT NULL DEFAULT 0,
    narratives_created          INTEGER NOT NULL DEFAULT 0,
    insights_created            INTEGER NOT NULL DEFAULT 0,
    config_hash                 TEXT,
    error_message               TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_memory_natural_runs_once_per_day
ON memory_natural_runs(persona_id, run_kind, local_date)
WHERE run_kind = 'sleep_cycle' AND status = 'completed' AND force = 0;

CREATE TABLE IF NOT EXISTS memory_natural_compression_candidates (
    id                          TEXT PRIMARY KEY,
    run_id                      TEXT,
    persona_id                  TEXT NOT NULL,
    cluster_key                 TEXT NOT NULL,
    target_node_type            TEXT NOT NULL
        CHECK (target_node_type IN ('narrative', 'insight')),
    source_refs_json            TEXT NOT NULL,
    candidate_summary           TEXT,
    avg_retrievability          REAL,
    avg_importance              REAL,
    min_confidence              REAL,
    status                      TEXT NOT NULL DEFAULT 'emitted'
        CHECK (status IN ('emitted', 'applied', 'rejected', 'skipped')),
    reason_codes_json           TEXT,
    created_at                  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TEXT
);


-- Begin 0010_pending_manual_forget_operations.sql
CREATE TABLE IF NOT EXISTS pending_manual_forget_operations (
    id                    TEXT PRIMARY KEY,
    persona_id            TEXT NOT NULL,
    session_id            TEXT,
    chat_session_id       TEXT,
    request_episode_id    TEXT,
    status                TEXT NOT NULL
        CHECK (status IN ('pending_confirmation', 'executed', 'cancelled', 'failed')),
    requested_level       TEXT NOT NULL
        CHECK (requested_level IN ('soft_forget', 'hard_forget', 'source_redact', 'purge')),
    scope_mode            TEXT,
    requires_confirmation INTEGER NOT NULL DEFAULT 0
        CHECK (requires_confirmation IN (0, 1)),
    candidates_json       TEXT NOT NULL,
    confirmation_policy_json TEXT,
    created_at            TEXT NOT NULL,
    updated_at            TEXT NOT NULL,
    expires_at            TEXT NOT NULL,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL,
    FOREIGN KEY (request_episode_id) REFERENCES episodes(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_pending_manual_forget_lookup
    ON pending_manual_forget_operations(persona_id, session_id, chat_session_id, status, expires_at);

CREATE INDEX IF NOT EXISTS idx_pending_manual_forget_updated
    ON pending_manual_forget_operations(persona_id, updated_at);


-- Begin 0011_semantic_ops.sql
-- Semantic operation metadata and safe decision audit.

CREATE TABLE IF NOT EXISTS semantic_mirror_meta (
    id                    TEXT PRIMARY KEY,
    persona_id            TEXT NOT NULL,
    node_type             TEXT NOT NULL,
    node_id               TEXT NOT NULL,
    doc_kind              TEXT NOT NULL,
    mirror_node_id         TEXT,
    content_fingerprint   TEXT NOT NULL,
    text_hash             TEXT NOT NULL,
    embedding_model       TEXT,
    embedding_dims        INTEGER,
    embedding_version     TEXT,
    index_status          TEXT NOT NULL DEFAULT 'pending',
    indexed_at            TEXT,
    deleted_at            TEXT,
    updated_at            TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(persona_id, node_type, node_id, doc_kind)
);

CREATE TABLE IF NOT EXISTS semantic_decision_audit (
    id                  TEXT PRIMARY KEY,
    request_id           TEXT NOT NULL,
    persona_id           TEXT NOT NULL,
    decision_type        TEXT NOT NULL,
    actor                TEXT NOT NULL DEFAULT 'system',
    reason_code          TEXT,
    candidate_hash       TEXT,
    selected_node_ids    TEXT,
    preview_hash         TEXT,
    policy_snapshot      TEXT,
    similarity_scores    TEXT,
    sidecar_status       TEXT NOT NULL,
    diagnostics_json     TEXT,
    created_at           TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- Begin 0012_memory_delta_curation.sql
-- 0012_memory_delta_curation.sql
-- Audit and checkpoint tables for Delta Memory Curation.


CREATE TABLE IF NOT EXISTS memory_curation_checkpoints (
    persona_id                 TEXT PRIMARY KEY,
    last_successful_run_id      TEXT,
    cursor_created_at           TEXT,
    cursor_fact_id              TEXT,
    updated_at                  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS memory_curation_runs (
    id                          TEXT PRIMARY KEY,
    persona_id                  TEXT NOT NULL,
    mode                        TEXT NOT NULL
        CHECK (mode IN ('dry_run', 'apply')),
    trigger                     TEXT NOT NULL
        CHECK (trigger IN ('manual', 'scheduled', 'cli', 'test')),
    status                      TEXT NOT NULL
        CHECK (status IN ('running', 'succeeded', 'partially_failed', 'failed', 'skipped')),

    cursor_from_created_at       TEXT,
    cursor_from_fact_id          TEXT,
    cursor_to_created_at         TEXT,
    cursor_to_fact_id            TEXT,

    new_fact_count               INTEGER NOT NULL DEFAULT 0,
    group_count                  INTEGER NOT NULL DEFAULT 0,
    llm_group_count              INTEGER NOT NULL DEFAULT 0,
    applied_group_count          INTEGER NOT NULL DEFAULT 0,
    review_group_count           INTEGER NOT NULL DEFAULT 0,
    noop_group_count             INTEGER NOT NULL DEFAULT 0,
    error_count                  INTEGER NOT NULL DEFAULT 0,

    provider_id                  TEXT,
    provider_kind                TEXT,
    model                       TEXT,
    usage_json                   TEXT,

    sanitized_error_code          TEXT,
    sanitized_error_message       TEXT,

    started_at                   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at                  TEXT,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS memory_curation_groups (
    id                          TEXT PRIMARY KEY,
    run_id                      TEXT NOT NULL,
    persona_id                  TEXT NOT NULL,

    group_status                TEXT NOT NULL
        CHECK (group_status IN ('planned', 'applied', 'noop', 'needs_review', 'failed')),

    decision                    TEXT NOT NULL
        CHECK (decision IN (
            'no_op',
            'reinforce_existing',
            'merge_into_existing',
            'create_canonical_fact',
            'coexist_related',
            'conflict_needs_review',
            'needs_review'
        )),

    semantic_relation            TEXT NOT NULL
        CHECK (semantic_relation IN (
            'same',
            'refinement',
            'overlap',
            'complement',
            'distinct',
            'conflict',
            'unclear'
        )),

    answer_gain                  TEXT NOT NULL
        CHECK (answer_gain IN ('none', 'small', 'material', 'unknown')),

    confidence                   REAL NOT NULL DEFAULT 0.0
        CHECK (confidence >= 0.0 AND confidence <= 1.0),

    canonical_fact_id            TEXT,
    merged_content_summary       TEXT,
    canonical_subject_entity_id  TEXT,
    canonical_predicate          TEXT,
    canonical_object_literal     TEXT,
    canonical_object_entity_id   TEXT,
    fact_type                    TEXT,

    reason_codes_json            TEXT,
    llm_response_hash            TEXT,
    sanitized_error_code          TEXT,
    sanitized_error_message       TEXT,

    created_at                   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   TEXT,

    FOREIGN KEY (run_id) REFERENCES memory_curation_runs(id) ON DELETE CASCADE,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS memory_curation_group_facts (
    id                          TEXT PRIMARY KEY,
    group_id                    TEXT NOT NULL,
    persona_id                  TEXT NOT NULL,
    fact_id                     TEXT NOT NULL,
    role                        TEXT NOT NULL
        CHECK (role IN ('new_delta', 'existing_candidate', 'canonical', 'source')),
    latest_evidence_at           TEXT,
    created_at                   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (group_id) REFERENCES memory_curation_groups(id) ON DELETE CASCADE,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (fact_id) REFERENCES facts(id) ON DELETE CASCADE,
    UNIQUE (group_id, fact_id, role)
);

CREATE INDEX IF NOT EXISTS idx_memory_curation_runs_persona_started
    ON memory_curation_runs(persona_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_curation_groups_run
    ON memory_curation_groups(run_id, group_status);
CREATE INDEX IF NOT EXISTS idx_memory_curation_group_facts_group
    ON memory_curation_group_facts(group_id, role);


-- Begin 0013_natural_memory_quota_index.sql
-- 0013_natural_memory_quota_index.sql
-- Harden Natural Memory sleep-cycle quota after the initial ledger rollout.

UPDATE memory_natural_runs
SET mark_sleep_cycle = 0
WHERE run_kind != 'sleep_cycle'
  AND mark_sleep_cycle = 1
  AND status = 'completed'
  AND force = 0
  AND EXISTS (
      SELECT 1
      FROM memory_natural_runs AS sleep
      WHERE sleep.persona_id = memory_natural_runs.persona_id
        AND sleep.local_date = memory_natural_runs.local_date
        AND sleep.run_kind = 'sleep_cycle'
        AND sleep.status = 'completed'
        AND sleep.force = 0
  );

UPDATE memory_natural_runs
SET mark_sleep_cycle = 0
WHERE run_kind != 'sleep_cycle'
  AND mark_sleep_cycle = 1
  AND status = 'completed'
  AND force = 0
  AND rowid NOT IN (
      SELECT MIN(rowid)
      FROM memory_natural_runs
      WHERE run_kind != 'sleep_cycle'
        AND mark_sleep_cycle = 1
        AND status = 'completed'
        AND force = 0
      GROUP BY persona_id, local_date
  );

CREATE UNIQUE INDEX IF NOT EXISTS idx_memory_natural_quota_once_per_day
ON memory_natural_runs(persona_id, local_date)
WHERE (run_kind = 'sleep_cycle' OR mark_sleep_cycle = 1) AND status = 'completed' AND force = 0;


