-- 0001_memory_foundation.sql
-- EmoAgent MemoryGraph v2 authoritative SQLite foundation.
-- Apply with foreign keys enabled. IDs are ULID-compatible TEXT generated by application code.

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;
PRAGMA busy_timeout = 5000;

CREATE TABLE IF NOT EXISTS schema_migrations (
    version          TEXT PRIMARY KEY,
    description      TEXT NOT NULL,
    applied_at       TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS personas (
    id                 TEXT PRIMARY KEY,
    display_name       TEXT NOT NULL,
    description        TEXT,
    status             TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'disabled', 'archived')),
    created_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
    id                 TEXT PRIMARY KEY,
    persona_id         TEXT NOT NULL,
    channel            TEXT NOT NULL DEFAULT 'webui'
        CHECK (channel IN ('webui', 'telegram', 'qq', 'cli', 'api', 'imported', 'other')),
    external_ref       TEXT,
    started_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at           TEXT,
    title              TEXT,
    summary            TEXT,
    visibility_status  TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'redacted', 'purged')),
    created_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TEXT,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    CHECK (ended_at IS NULL OR ended_at >= started_at)
);

CREATE TABLE IF NOT EXISTS episodes (
    id                 TEXT PRIMARY KEY,
    persona_id         TEXT NOT NULL,
    session_id         TEXT NOT NULL,
    role               TEXT NOT NULL
        CHECK (role IN ('user', 'assistant', 'system', 'tool_summary', 'work_report')),
    content            TEXT NOT NULL,
    content_hash       TEXT NOT NULL,
    occurred_at        TEXT NOT NULL,
    ingested_at        TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_type        TEXT NOT NULL
        CHECK (source_type IN ('chat', 'work_candidate', 'plugin', 'system', 'imported')),
    source_ref         TEXT,
    prev_episode_id    TEXT,
    next_episode_id    TEXT,
    visibility_status  TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'redacted', 'purged')),
    sensitivity_level  TEXT NOT NULL DEFAULT 'normal'
        CHECK (sensitivity_level IN ('normal', 'sensitive', 'highly_sensitive')),
    searchable         INTEGER NOT NULL DEFAULT 1
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (prev_episode_id) REFERENCES episodes(id) ON DELETE SET NULL,
    FOREIGN KEY (next_episode_id) REFERENCES episodes(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS episode_tombstones (
    episode_id                    TEXT PRIMARY KEY,
    persona_id                    TEXT NOT NULL,
    session_id                    TEXT,
    occurred_at                   TEXT,
    redacted_at                   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    redaction_level               TEXT NOT NULL
        CHECK (redaction_level IN ('source_redact', 'purge')),
    redaction_actor               TEXT NOT NULL
        CHECK (redaction_actor IN ('user', 'system', 'admin')),
    redaction_reason_code          TEXT NOT NULL
        CHECK (redaction_reason_code IN ('user_requested', 'retention_policy', 'safety', 'admin_policy')),
    source_type                   TEXT,
    source_ref_hash               TEXT,
    content_hash_before_redaction TEXT,
    audit_note                    TEXT,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS entities (
    id                 TEXT PRIMARY KEY,
    persona_id         TEXT NOT NULL,
    canonical_name     TEXT NOT NULL,
    entity_type        TEXT NOT NULL
        CHECK (entity_type IN ('user', 'agent', 'person', 'place', 'org', 'concept', 'object', 'event_topic')),
    description        TEXT,
    created_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TEXT,
    visibility_status  TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'forgotten', 'purged')),
    sensitivity_level  TEXT NOT NULL DEFAULT 'normal'
        CHECK (sensitivity_level IN ('normal', 'sensitive', 'highly_sensitive')),
    searchable         INTEGER NOT NULL DEFAULT 1
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS entity_aliases (
    id                 TEXT PRIMARY KEY,
    persona_id         TEXT NOT NULL,
    entity_id          TEXT NOT NULL,
    alias              TEXT NOT NULL,
    alias_type         TEXT NOT NULL DEFAULT 'surface'
        CHECK (alias_type IN ('surface', 'nickname', 'translation', 'abbreviation')),
    confidence         REAL NOT NULL DEFAULT 1.0
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    source_episode_id  TEXT,
    created_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE,
    FOREIGN KEY (source_episode_id) REFERENCES episodes(id) ON DELETE SET NULL,
    UNIQUE (persona_id, entity_id, alias, alias_type)
);

CREATE TABLE IF NOT EXISTS facts (
    id                         TEXT PRIMARY KEY,
    persona_id                 TEXT NOT NULL,
    subject_entity_id           TEXT,
    predicate                   TEXT NOT NULL,
    object_entity_id            TEXT,
    object_literal              TEXT,
    content_summary             TEXT NOT NULL,
    fact_type                   TEXT NOT NULL
        CHECK (fact_type IN (
            'core_identity',
            'significant_event',
            'stable_preference',
            'relational_state',
            'commitment',
            'transient_context',
            'task_relevant_context'
        )),
    valid_from                  TEXT,
    valid_to                    TEXT,
    ingested_at                 TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    extraction_confidence       TEXT NOT NULL
        CHECK (extraction_confidence IN ('explicit', 'inferred', 'ambiguous')),
    extraction_confidence_score REAL NOT NULL DEFAULT 0.5
        CHECK (extraction_confidence_score >= 0.0 AND extraction_confidence_score <= 1.0),
    extraction_reasoning        TEXT,
    importance                  REAL NOT NULL DEFAULT 0.5
        CHECK (importance >= 0.0 AND importance <= 1.0),
    valence                     REAL NOT NULL DEFAULT 0.0
        CHECK (valence >= -1.0 AND valence <= 1.0),
    arousal                     REAL NOT NULL DEFAULT 0.0
        CHECK (arousal >= 0.0 AND arousal <= 1.0),
    sensitivity_level           TEXT NOT NULL DEFAULT 'normal'
        CHECK (sensitivity_level IN ('normal', 'sensitive', 'highly_sensitive')),
    validity_status             TEXT NOT NULL DEFAULT 'valid'
        CHECK (validity_status IN ('valid', 'invalidated', 'uncertain')),
    visibility_status           TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'forgotten', 'purged')),
    lifecycle_status            TEXT NOT NULL DEFAULT 'active'
        CHECK (lifecycle_status IN ('active', 'dormant', 'consolidated', 'archived', 'deep_archived')),
    pinned                      INTEGER NOT NULL DEFAULT 0
        CHECK (pinned IN (0, 1)),
    pin_reason                  TEXT,
    pin_actor                   TEXT
        CHECK (pin_actor IS NULL OR pin_actor IN ('user', 'system', 'admin')),
    pinned_at                   TEXT,
    access_count                INTEGER NOT NULL DEFAULT 0
        CHECK (access_count >= 0),
    last_accessed_at            TEXT,
    reinforcement_count         INTEGER NOT NULL DEFAULT 0
        CHECK (reinforcement_count >= 0),
    congruent_access_count      INTEGER NOT NULL DEFAULT 0
        CHECK (congruent_access_count >= 0),
    searchable                  INTEGER NOT NULL DEFAULT 1
        CHECK (searchable IN (0, 1)),
    created_at                  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TEXT,
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    FOREIGN KEY (subject_entity_id) REFERENCES entities(id) ON DELETE SET NULL,
    FOREIGN KEY (object_entity_id) REFERENCES entities(id) ON DELETE SET NULL,
    CHECK (
        object_entity_id IS NOT NULL
        OR object_literal IS NOT NULL
        OR visibility_status IN ('forgotten', 'purged')
    ),
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from),
    CHECK ((pinned = 0 AND pinned_at IS NULL) OR (pinned = 1))
);

CREATE TABLE IF NOT EXISTS narratives (
    id                    TEXT PRIMARY KEY,
    persona_id            TEXT NOT NULL,
    scope                 TEXT NOT NULL
        CHECK (scope IN ('day', 'week', 'month', 'topic', 'relationship_phase', 'project')),
    scope_ref             TEXT,
    summary               TEXT NOT NULL,
    emotional_tone        TEXT,
    valence_avg           REAL
        CHECK (valence_avg IS NULL OR (valence_avg >= -1.0 AND valence_avg <= 1.0)),
    arousal_avg           REAL
        CHECK (arousal_avg IS NULL OR (arousal_avg >= 0.0 AND arousal_avg <= 1.0)),
    importance            REAL NOT NULL DEFAULT 0.5
        CHECK (importance >= 0.0 AND importance <= 1.0),
    valid_from            TEXT,
    valid_to              TEXT,
    generated_at          TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    visibility_status     TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'forgotten', 'purged')),
    lifecycle_status      TEXT NOT NULL DEFAULT 'active'
        CHECK (lifecycle_status IN ('active', 'dormant', 'consolidated', 'archived', 'deep_archived')),
    sensitivity_level     TEXT NOT NULL DEFAULT 'normal'
        CHECK (sensitivity_level IN ('normal', 'sensitive', 'highly_sensitive')),
    searchable            INTEGER NOT NULL DEFAULT 1
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

CREATE TABLE IF NOT EXISTS insights (
    id                    TEXT PRIMARY KEY,
    persona_id            TEXT NOT NULL,
    insight_type          TEXT NOT NULL
        CHECK (insight_type IN ('pattern', 'trait', 'preference', 'boundary', 'coping_strategy', 'risk_signal')),
    content               TEXT NOT NULL,
    confidence            REAL NOT NULL DEFAULT 0.5
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    importance            REAL NOT NULL DEFAULT 0.5
        CHECK (importance >= 0.0 AND importance <= 1.0),
    valence               REAL NOT NULL DEFAULT 0.0
        CHECK (valence >= -1.0 AND valence <= 1.0),
    arousal               REAL NOT NULL DEFAULT 0.0
        CHECK (arousal >= 0.0 AND arousal <= 1.0),
    created_at            TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TEXT,
    visibility_status     TEXT NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden', 'forgotten', 'purged')),
    lifecycle_status      TEXT NOT NULL DEFAULT 'active'
        CHECK (lifecycle_status IN ('active', 'dormant', 'consolidated', 'archived', 'deep_archived')),
    sensitivity_level     TEXT NOT NULL DEFAULT 'normal'
        CHECK (sensitivity_level IN ('normal', 'sensitive', 'highly_sensitive')),
    searchable            INTEGER NOT NULL DEFAULT 1
        CHECK (searchable IN (0, 1)),
    FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sessions_persona_started
    ON sessions(persona_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_visibility
    ON sessions(persona_id, visibility_status, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_episodes_persona_session_time
    ON episodes(persona_id, session_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_episodes_persona_time
    ON episodes(persona_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_episodes_content_hash
    ON episodes(persona_id, content_hash);
CREATE INDEX IF NOT EXISTS idx_episodes_prev
    ON episodes(persona_id, prev_episode_id);
CREATE INDEX IF NOT EXISTS idx_episodes_next
    ON episodes(persona_id, next_episode_id);
CREATE INDEX IF NOT EXISTS idx_episodes_visible_searchable
    ON episodes(persona_id, occurred_at DESC)
    WHERE visibility_status = 'visible' AND searchable = 1;

CREATE INDEX IF NOT EXISTS idx_episode_tombstones_persona_time
    ON episode_tombstones(persona_id, redacted_at DESC);

CREATE INDEX IF NOT EXISTS idx_entities_persona_type_name
    ON entities(persona_id, entity_type, canonical_name);
CREATE INDEX IF NOT EXISTS idx_entities_persona_visible
    ON entities(persona_id, visibility_status, searchable);
CREATE INDEX IF NOT EXISTS idx_entity_aliases_persona_alias
    ON entity_aliases(persona_id, alias);
CREATE INDEX IF NOT EXISTS idx_entity_aliases_entity
    ON entity_aliases(entity_id);

CREATE INDEX IF NOT EXISTS idx_facts_subject_predicate
    ON facts(persona_id, subject_entity_id, predicate);
CREATE INDEX IF NOT EXISTS idx_facts_object_entity
    ON facts(persona_id, object_entity_id);
CREATE INDEX IF NOT EXISTS idx_facts_predicate
    ON facts(persona_id, predicate);
CREATE INDEX IF NOT EXISTS idx_facts_type_lifecycle
    ON facts(persona_id, fact_type, lifecycle_status);
CREATE INDEX IF NOT EXISTS idx_facts_validity_visibility
    ON facts(persona_id, validity_status, visibility_status, searchable);
CREATE INDEX IF NOT EXISTS idx_facts_pinned
    ON facts(persona_id, pinned, importance DESC, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_facts_ingested
    ON facts(persona_id, ingested_at DESC);
CREATE INDEX IF NOT EXISTS idx_facts_valid_time
    ON facts(persona_id, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS idx_facts_active_searchable
    ON facts(persona_id, importance DESC, ingested_at DESC)
    WHERE visibility_status = 'visible'
      AND searchable = 1
      AND lifecycle_status IN ('active', 'dormant', 'consolidated')
      AND validity_status IN ('valid', 'uncertain');

CREATE INDEX IF NOT EXISTS idx_narratives_scope
    ON narratives(persona_id, scope, scope_ref, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_narratives_searchable
    ON narratives(persona_id, importance DESC, generated_at DESC)
    WHERE visibility_status = 'visible' AND searchable = 1;

CREATE INDEX IF NOT EXISTS idx_insights_type
    ON insights(persona_id, insight_type, confidence DESC, importance DESC);
CREATE INDEX IF NOT EXISTS idx_insights_searchable
    ON insights(persona_id, importance DESC, created_at DESC)
    WHERE visibility_status = 'visible' AND searchable = 1;

INSERT OR IGNORE INTO schema_migrations(version, description)
VALUES ('0001', 'MemoryGraph v2 foundation: personas, sessions, episodes, entities, facts, narratives, insights');
