package config

import (
	"fmt"
	"strings"
)

type FieldDescriptor struct {
	Field        string `json:"field"`
	Type         string `json:"type"`
	Default      string `json:"default"`
	Allowed      string `json:"allowed"`
	RequiredWhen string `json:"required_when"`
	Description  string `json:"description"`
}

func FieldDescriptors() []FieldDescriptor {
	return []FieldDescriptor{
		{"schema_version", "string", SchemaVersion, SchemaVersion, "optional", "Configuration contract version."},
		{"enabled", "bool", "false", "true|false", "always", "Embedding switch for parent applications; CLI commands still run when explicitly invoked."},
		{"core.db_path", "string", "./data/memory.db", "non-empty", "enabled=true", "SQLite database path."},
		{"core.persona_id", "string", "default", "non-empty", "always", "Persona ID used for service requests."},
		{"core.auto_migrate", "bool", "true", "true|false", "always", "Apply SQLite migrations when opening the service."},
		{"core.enable_fts", "bool", "true", "true|false", "always", "Enable optional FTS migrations when migrations run."},
		{"core.timezone", "string", "Asia/Shanghai", "IANA timezone", "always", "Default timezone for host-level scheduling and examples."},
		{"providers.llm[].id", "string", "default_llm", "non-empty unique provider id", "when provider entry exists", "Provider registry key used by LLM pipelines."},
		{"providers.llm[].provider", "string", "disabled", "provider name", "always", "Provider implementation label supplied by the host."},
		{"providers.llm[].protocol", "string", "openai_compatible", "provider protocol", "always", "Wire protocol expected by the host adapter."},
		{"providers.llm[].base_url", "string", "", "URL or env-expanded string", "provider-dependent", "Provider endpoint. Secrets must not be embedded here."},
		{"providers.llm[].api_key_env", "string", "", "environment variable name", "provider-dependent", "Environment variable that holds the secret API key."},
		{"providers.llm[].enabled", "bool", "false", "true|false", "always", "Whether the provider may be selected by pipelines."},
		{"providers.embedder[]", "[]provider", "default disabled", "same provider fields", "always", "Embedding provider registry."},
		{"providers.reranker[]", "[]provider", "default disabled", "same provider fields", "always", "Reranker provider registry."},
		{"pipelines.prefilter.provider_id", "string", "", "provider id", "prefilter.enabled=true", "LLM provider for prefiltering."},
		{"pipelines.extraction.provider_id", "string", "", "provider id", "extraction.enabled=true", "LLM provider for memory extraction."},
		{"pipelines.extraction.mode", "string", "dry-run", "validate|dry-run|dry_run|apply", "always", "Default extraction run mode used when a request does not override it."},
		{"pipelines.extraction.model", "string", "", "model id", "host-dependent", "Extraction model name."},
		{"pipelines.extraction.params.temperature", "float", "0.0", ">= 0", "always", "Extraction sampling temperature."},
		{"pipelines.extraction.params.top_p", "float", "1.0", "[0, 1]", "always", "Extraction nucleus sampling."},
		{"pipelines.extraction.params.max_output_tokens", "int", "6000", ">= 0", "always", "Extraction output cap."},
		{"pipelines.extraction.params.response_format", "string", "json_schema", "text|json_object|json_schema", "always", "Expected extraction response format."},
		{"pipelines.extraction.retry_on_schema_failure", "int", "1", ">= 0", "always", "Schema repair attempts after malformed extraction output."},
		{"pipelines.extraction.audit.enabled", "bool", "true", "true|false", "always", "Write sanitized extraction audit rows for fingerprinting and observability."},
		{"pipelines.extraction.audit.force", "bool", "false", "true|false", "always", "Ignore previous successful extraction audit fingerprints."},
		{"pipelines.extraction.raw_log.enabled", "bool", "false", "true|false", "always", "Write full raw extraction debug artifacts. Contains sensitive source text and prompts."},
		{"pipelines.extraction.raw_log.directory", "string", "", "directory path", "raw_log.enabled=true", "Directory for per-run raw extraction debug JSON files."},
		{"pipelines.query_analysis.mode", "string", "rule_only", "rule_only|rule_then_llm|llm_only|sidecar", "always", "Query-analysis orchestration mode; rule_only fallback is mandatory."},
		{"pipelines.query_analysis.runtime_mode", "string", "rule_only", "rule_only|shadow_adaptive|adaptive|adaptive_safe|adaptive_full|semantic_always|semantic_on_low_confidence|semantic_rewrite_only|legacy_only", "always", "Projection into the current Go runtime query-analysis mode."},
		{"pipelines.query_analysis.fallback_mode", "string", "rule_only", "rule_only", "always", "Safe retrieval fallback when LLM or sidecar query analysis fails."},
		{"pipelines.query_analysis.params.max_output_tokens", "int", "768", ">= 0", "always", "LLM query-analysis output cap."},
		{"pipelines.query_analysis.thresholds.min_rule_fit", "float", "0.66", "(0, 1]", "always", "Adaptive route minimum rule-fit score."},
		{"pipelines.query_analysis.budget.max_semantic_latency_ms", "int", "1500", "> 0", "always", "Maximum semantic query-analysis request latency budget."},
		{"semantic_ops.curation.enabled", "bool", "false", "true|false", "always", "Enable scheduled or host-triggered delta memory curation. Manual CLI runs may still force execution."},
		{"semantic_ops.curation.mode", "string", "dry_run", "dry_run|dry-run|apply", "always", "Default curation run mode."},
		{"semantic_ops.curation.schedule_enabled", "bool", "false", "true|false", "host-owned scheduler", "Enable host scheduler intent; MemoryCore does not start background loops by itself."},
		{"semantic_ops.curation.max_new_facts_per_run", "int", "100", "> 0", "always", "Maximum active/searchable delta facts scanned per curation run."},
		{"semantic_ops.curation.candidate_limit_per_fact", "int", "20", "> 0", "always", "Maximum comparable existing facts retrieved for each delta fact."},
		{"semantic_ops.curation.max_facts_per_group", "int", "8", "> 1", "always", "Maximum facts sent to one semantic curation LLM group."},
		{"semantic_ops.curation.min_auto_apply_confidence", "float", "0.88", "[0, 1]", "always", "Minimum confidence for automatic same/refinement curation apply."},
		{"semantic_ops.curation.candidate_retrieval.mode", "string", "mirror_first", "mirror_first|sqlite_only|mirror_only", "always", "Candidate source for comparable fact retrieval."},
		{"semantic_ops.curation.candidate_retrieval.mirror_min_similarity", "float", "0.70", "(0, 1]", "mirror modes", "Minimum mirror similarity allowed to connect a curation group edge."},
		{"semantic_ops.curation.include_fact_types", "[]string", "stable_preference, relational_state, transient_context, task_relevant_context", "fact type list", "always", "Fact types eligible for delta curation."},
		{"semantic_ops.curation.exclude_fact_types", "[]string", "core_identity, commitment", "fact type list", "always", "Fact types excluded from automatic source consolidation."},
		{"semantic_ops.curation.raw_log.enabled", "bool", "false", "true|false", "always", "Write full raw curation debug artifacts. Contains sensitive prompt and provider data."},
		{"semantic_ops.curation.raw_log.directory", "string", "", "directory path", "raw_log.enabled=true", "Directory for per-run raw curation debug JSON files."},
		{"semantic_ops.curation.llm.provider_id", "string", "default_llm", "provider id", "curation.enabled=true unless provider_kind=mock", "LLM provider used for semantic curation analysis."},
		{"semantic_ops.curation.llm.provider_kind", "string", "", "mock|openai-compatible|disabled", "optional", "Provider implementation override for curation tests or CLI runs."},
		{"semantic_ops.curation.llm.model", "string", "memory-curator", "model id", "host-dependent", "Curation analysis model name."},
		{"semantic_ops.curation.llm.response_format", "string", "json_object", "json_object", "always", "OpenAI-compatible response format for curation JSON decisions."},
		{"semantic_ops.curation.llm.timeout_ms", "int", "60000", "> 0", "always", "Curation LLM request timeout."},
		{"semantic_ops.curation.llm.thinking.type", "string", "disabled", "disabled|enabled", "always", "OpenAI-compatible thinking control; enabled parses reasoning_content instead of content."},
		{"natural_memory.enabled", "bool", "true", "true|false", "always", "Enable independent Natural Memory Dynamics runs."},
		{"natural_memory.algorithm_version", "string", "natural_power_sleep_v1", "natural_power_sleep_v1", "always", "Natural memory scoring algorithm version."},
		{"natural_memory.sleep_cycle.local_time", "string", "03:30", "HH:mm", "sleep_cycle.enabled=true", "Local daily sleep-cycle time."},
		{"natural_memory.sleep_cycle.min_interval_hours", "int", "20", ">= 1", "always", "Minimum interval between completed sleep cycles."},
		{"natural_memory.sleep_cycle.run_missed_on_start", "bool", "false", "true|false", "host startup tick", "Allow a startup tick to run a missed sleep cycle after the configured night window."},
		{"natural_memory.sleep_cycle.jitter_minutes", "int", "0", ">= 0", "sleep_cycle.enabled=true", "Deterministic per-persona delay added to local_time."},
		{"natural_memory.sleep_cycle.night_window_start", "string", "01:00", "HH:mm", "sleep_cycle.enabled=true", "Start of the expected night window for warnings."},
		{"natural_memory.sleep_cycle.night_window_end", "string", "05:00", "HH:mm", "sleep_cycle.enabled=true", "End of the expected night window for warnings."},
		{"natural_memory.sleep_cycle.warn_if_outside_night_window", "bool", "true", "true|false", "always", "Add an explain warning when a sleep cycle runs outside the night window."},
		{"natural_memory.manual_trigger.enabled", "bool", "true", "true|false", "always", "Allow manual natural-memory-run invocations."},
		{"natural_memory.scoring.reactivation_threshold", "float", "0.55", "[0, 1.5]", "always", "Selective reactivation threshold."},
		{"natural_memory.scoring.first_sleep_window_hours", "int", "36", "> 0", "always", "One-time first-sleep consolidation window."},
		{"natural_memory.search_tier.update_only_search_tier_and_updated_at", "bool", "true", "must remain true", "always", "Natural Memory only writes search_tier and updated_at on search documents."},
		{"natural_memory.compression.emit_candidates", "bool", "true", "true|false", "always", "Emit compression candidates without changing source lifecycle."},
		{"natural_memory.limits.max_candidates_per_run", "int", "5000", "> 0", "always", "Maximum natural memory candidates scanned per run."},
		{"pipelines.embedding.provider_id", "string", "default_embedder", "provider id", "embedding.enabled=true", "Embedding provider id."},
		{"pipelines.rerank.provider_id", "string", "default_reranker", "provider id", "rerank.enabled=true", "Reranker provider id."},
		{"write_policy.triggers.idle_detect.enabled", "bool", "true", "true|false", "always", "Enable idle detection trigger."},
		{"write_policy.triggers.manual_forget.enabled", "bool", "true", "true|false", "legacy", "Legacy manual forget trigger; deletion intents are handled by background extraction."},
		{"write_policy.triggers.work_candidate.enabled", "bool", "true", "true|false", "always", "Enable Emotion-approved work candidate trigger."},
		{"write_policy.extraction.allow_inference", "bool", "true", "true|false", "always", "Permit inference during extraction."},
		{"write_policy.extraction.allow_sensitive_extraction", "bool", "false", "true|false", "always", "Permit sensitive extraction; defaults conservative."},
		{"write_policy.extraction.max_facts_per_request", "int", "12", "> 0", "always", "Maximum fact candidates per extraction request."},
		{"write_policy.prefilter.route_manual_forget_always", "bool", "true", "true|false", "legacy", "Legacy manual forget prefilter switch; session_end deletion intents are handled by background extraction."},
		{"retrieval.use_fts", "bool", "true", "true|false", "always", "Use SQLite FTS candidates when available."},
		{"retrieval.use_mirror", "bool", "false", "true|false", "always", "Use sidecar mirror candidates as non-authoritative hints."},
		{"retrieval.final_memory_count", "int", "8", "> 0", "always", "Maximum final memory items."},
		{"retrieval.context_budget_tokens", "int", "1200", "> 0", "always", "Context budget for retrieved memory blocks."},
		{"retrieval.sensitivity_permission", "string", "normal", "normal|sensitive|highly_sensitive", "always", "Maximum sensitivity level allowed for retrieval."},
		{"retrieval.anchor.max_entity_anchors", "int", "20", ">= 0", "always", "Entity anchor budget."},
		{"retrieval.activation.max_hops", "int", "2", "> 0", "always", "Graph activation hop budget."},
		{"retrieval.activation.max_hops_for_historical_or_causal", "int", "3", "> 0", "always", "Graph activation hop budget for historical or causal queries."},
		{"retrieval.ranking.candidate_pool_size", "int", "80", "> 0", "always", "Candidate pool size before final ranking."},
		{"retrieval.ranking.agent_affect_weight_cap", "float", "0.03", "[0, 0.03]", "always", "Maximum Agent Affect ranking contribution."},
		{"retrieval_scoring.profile", "string", "retrieval_v5d_default", "non-empty", "always", "Versioned Go authority retrieval scoring profile."},
		{"retrieval_scoring.weights.anchor_energy", "float", "0.55", ">= 0", "always", "Anchor energy final-score weight."},
		{"retrieval_scoring.weights.graph_energy", "float", "0.25", ">= 0", "always", "Graph activation final-score weight."},
		{"retrieval_scoring.weights.importance", "float", "0.20", ">= 0", "always", "Fact importance final-score weight."},
		{"retrieval_scoring.weights.recency", "float", "0.10", ">= 0", "always", "Recency final-score weight."},
		{"retrieval_scoring.weights.fact_type_prior", "float", "0.10", ">= 0", "always", "Fact type prior final-score weight."},
		{"retrieval_scoring.weights.evidence_strength", "float", "0.10", ">= 0", "always", "Evidence strength final-score weight."},
		{"retrieval_scoring.weights.pinned", "float", "0.05", ">= 0", "always", "Pinned fact final-score weight."},
		{"retrieval_scoring.weights.lexical_coverage", "float", "0.12", ">= 0", "always", "Lexical coverage final-score weight."},
		{"retrieval_scoring.weights.slot_boost", "float", "1.00", ">= 0", "always", "Slot coverage boost multiplier."},
		{"retrieval_scoring.weights.reflection_boost", "float", "1.00", ">= 0", "always", "Reflection boost multiplier."},
		{"retrieval_scoring.weights.completion_bonus", "float", "1.00", ">= 0", "always", "Completion bonus multiplier."},
		{"retrieval_scoring.weights.rerank_boost", "float", "0.08", ">= 0", "always", "Safe reranker boost weight."},
		{"retrieval_scoring.penalties.hub_suppression", "float", "1.00", ">= 0", "always", "Hub suppression penalty multiplier."},
		{"retrieval_scoring.penalties.premise_restatement", "float", "1.00", ">= 0", "always", "Premise restatement penalty multiplier."},
		{"retrieval_scoring.penalties.fatigue", "float", "1.00", ">= 0", "always", "Fatigue penalty multiplier."},
		{"retrieval_scoring.penalties.sensitivity", "float", "1.00", ">= 0", "always", "Sensitivity penalty multiplier."},
		{"retrieval_scoring.caps.agent_affect_affinity_max", "float", "0.03", "[0, 0.03]", "always", "Maximum future Agent Affect affinity contribution."},
		{"retrieval_scoring.caps.negative_mood_congruence_max", "float", "0.00", "0.00", "always", "Negative mood congruence is disabled in this version."},
		{"retrieval.mmr.enabled", "bool", "true", "true|false", "always", "Enable MMR diversity selection."},
		{"retrieval.mmr.lambda", "float", "0.72", "[0, 1]", "always", "MMR relevance/diversity balance."},
		{"sidecar.enabled", "bool", "false", "true|false", "always", "Enable a Go-side mirror adapter."},
		{"sidecar.url", "string", "", "loopback HTTP URL", "sidecar.enabled=true and adapter=trivium", "Python sidecar base URL."},
		{"sidecar.adapter", "string", "trivium", "fake|trivium", "always", "Mirror adapter implementation."},
		{"sidecar.total_timeout_ms", "int", "2500", "> 0", "always", "Total sidecar retrieval stage budget."},
		{"sidecar.circuit_breaker.enabled", "bool", "true", "true|false", "always", "Enable persona/stage circuit breakers for sidecar retrieval stages."},
		{"sidecar.activation_budget.max_edges_scanned_per_request", "int", "10000", "> 0", "always", "Python graph activation edge scan budget."},
		{"mirror.enabled", "bool", "false", "true|false", "always", "Enable mirror maintenance behavior."},
		{"mirror.sync_limit", "int", "100", "> 0", "always", "Maximum mirror queue rows to process."},
		{"mirror.rebuild_on_start", "bool", "false", "true|false", "always", "Whether host startup should rebuild mirror state."},
		{"mirror.stale_lag_threshold_ms", "int", "30000", ">= 0", "always", "Mirror staleness alert threshold."},
		{"retention.jobs.daily_ttl_expiry", "bool", "true", "true|false", "always", "Run daily TTL expiry job."},
		{"retention.jobs.monthly_archive", "bool", "false", "true|false", "always", "Run monthly archive-to-deep-archive job."},
		{"retention.thresholds.deep_archive_after_days", "int", "0", "> 0 when monthly_archive=true", "monthly_archive", "Archive age threshold for monthly deep archive."},
		{"retention.auto_delete", "bool", "false", "must remain false", "always", "Automatic deletion is disabled in this phase."},
		{"forgetting_privacy.default_forget_level", "string", "soft_forget", "soft_forget|hard_forget|purge|source_redact", "always", "Default forget level for host confirmations."},
		{"forgetting_privacy.cleanup.delete_trivium_nodes", "bool", "true", "true|false", "always", "Attempt mirror cleanup after SQLite forget/purge."},
		{"forgetting_privacy.cleanup.delete_sqlite_search_documents", "bool", "true", "true|false", "always", "Delete SQLite search documents during privacy cleanup."},
		{"agent_affect.enabled", "bool", "false", "true|false", "always", "Enable Agent Affect placeholder integration."},
		{"agent_affect.storage_enabled", "bool", "true", "true|false", "always", "Allow internal Agent Affect state storage."},
		{"agent_affect.safety.allow_user_fact_writes", "bool", "false", "must remain false", "always", "Agent Affect must not write user facts."},
		{"agent_affect.safety.allow_sensitivity_bypass", "bool", "false", "must remain false", "always", "Agent Affect must not bypass sensitivity filters."},
		{"agent_affect.safety.allow_forget_bypass", "bool", "false", "must remain false", "always", "Agent Affect must not bypass forget or purge."},
		{"agent_affect.retrieval.weight_cap", "float", "0.03", "[0, 0.03]", "always", "Maximum Agent Affect retrieval contribution."},
		{"agent_affect.retrieval.sensitive_recall", "string", "disallow", "disallow", "always", "Agent Affect sensitive recall policy."},
		{"observability.metrics_enabled", "bool", "true", "true|false", "always", "Enable sanitized metrics."},
		{"observability.log_sanitized_debug", "bool", "true", "true|false", "always", "Allow sanitized debug logs."},
		{"eval.enabled", "bool", "false", "true|false", "optional", "Enable eval-specific host behavior."},
	}
}

func MarkdownReference() string {
	var builder strings.Builder
	builder.WriteString("| Field | Type | Default | Allowed | Required When | Description |\n")
	builder.WriteString("| --- | --- | --- | --- | --- | --- |\n")
	for _, field := range FieldDescriptors() {
		fmt.Fprintf(&builder, "| `%s` | %s | `%s` | %s | %s | %s |\n",
			field.Field,
			field.Type,
			field.Default,
			field.Allowed,
			field.RequiredWhen,
			field.Description,
		)
	}
	return builder.String()
}
